name=iotFeagri
version=1.1.0
author=Leandro Morais (FEAGRI-UNICAMP)
maintainer=Leandro Morais
sentence=Biblioteca para simplificar o provisionamento e telemetria no ecossistema IoT FEAGRI.
paragraph=Facilita o uso de MQTT, provisionamento via Captive Portal (192.168.4.1), salvamento em NVS e atualizações OTA para pesquisadores e alunos da UNICAMP.
category=Communication
url=https://github.com/morais-lab/iotFeagri
architectures=esp32
depends=ArduinoJson, PubSubClient
